### ISSUE TITLE
Command sent to VARNA is printed

### ISSUE THREAD

**Issue by lemora** [anthonyhtyao/varnaapi#2]
When saving a generated secondary structure to file, the command that is sent to VARNA is printed, which is annoying and likely unnecessary:

https://github.com/anthonyhtyao/varnaapi/blob/05e91a5ce5915a742868a6b24fb3c4d6497dbb95/src/varnaapi/models.py#L340

If possible, it would be great if you could remove it.

**Comment by anthonyhtyao** [comment]
fair point. Will make it in the next release

**Comment by anthonyhtyao** [comment]
Included in v1.2.0
