### ISSUE TITLE
Feature request; Structure object

### ISSUE THREAD

**Issue by jwbear** [anthonyhtyao/varnaapi#4]
Maybe the structure object could inherit attributes from the varnaapi, and then we can update attributes in one statement and save all the configurations to a file using the structure object as well.

**Comment by anthonyhtyao** [comment]
can you elaborate more about the idea?

**Comment by jwbear** [comment]
So, I don't remember exactly, but I think I was referring to extracting the data from the Structure object when writing to a file. Since I was writing the bpseq with my own function, I wanted to also extract all the configurations and write them out as well, but they are applied to varnaapi and it's more difficult to extract them. It wouldn't work anyway though because I also don't see a good way to load the configurations into the java applet for manipulation. I'll close the issue. Thanks for responding!
